name: sbom-scan
on: 
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Try to list files
        run: ls

      - name: Pull the code
        uses: actions/checkout@v6.0.2

      - name: Try to list files
        run: ls

      - name: Install cyclonedx-bom tool
        run: pipx install cyclonedx-bom
      
      - name: run cyclonedx-py 
        run: cyclonedx-py requirements -o sbom.xml --of XML

      - name: Try to list files
        run: ls

      - name: "upload sbom result"
        uses: actions/upload-artifact@v7.0.1
        with:
           name: sbom.xml
           path: ${{github.workspace}}
