name: "secret_scanner"
on: 
  schedule: 
    - cron: '*/5 * * * *'

jobs:
  secret_scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Try to list files
        run: ls
    
      - uses: actions/checkout@v4

      - name: Try to list files
        run: ls
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.95.3
