name: "secret_scanner"
on: 
  workflow_dispatch:

jobs:
  secret_scanner:
    runs-on: ubuntu-latest

    steps:
      - name: pull the code
        uses: actions/checkout@v6.0.2

      - name: list files
        run: ls
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.95.3
